when:
  event:
    - push
    - tag

steps:
  - name: test
    image: golang:1.22-alpine
    commands:
      - go test ./...
      - go vet ./...
    when:
      event:
        - push
      branch:
        - main

  - name: build-and-push
    image: plugins/docker
    settings:
      registry: registry.codeberg.org
      repo: registry.codeberg.org/${CI_REPO}
      tags:
        - latest
        - ${DRONE_TAG##v}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      daemon_off: true
      dockerfile: Dockerfile
    when:
      event:
        - tag
